C:\Users\a.azamov\.conda\envs\lulc\python.exe C:\Users\a.azamov\PycharmProjects\Land-Cover-Classification\instance-segmentation\prepare_yolo_data.py 
C:\Users\a.azamov\PycharmProjects\Land-Cover-Classification\instance-segmentation\prepare_yolo_data.py:111: RuntimeWarning: invalid value encountered in divide
  scaled_band = (band - band.min()) / (band.max() - band.min())
C:\Users\a.azamov\PycharmProjects\Land-Cover-Classification\instance-segmentation\prepare_yolo_data.py:115: RuntimeWarning: invalid value encountered in cast
  image = Image.fromarray((image_normalized * 255).astype(np.uint8))
Traceback (most recent call last):
  File "C:\Users\a.azamov\PycharmProjects\Land-Cover-Classification\instance-segmentation\prepare_yolo_data.py", line 147, in <module>
    geojson2yolo(geojson_path, image_path, set_name)
  File "C:\Users\a.azamov\PycharmProjects\Land-Cover-Classification\instance-segmentation\prepare_yolo_data.py", line 70, in geojson2yolo
    if len(points) == 1:
       ^^^^^^^^^^^
TypeError: object of type 'float' has no len()

Process finished with exit code 1
